version: '3.8'

services:
  speakai:
    image: ghcr.io/bentwnghk/speakai:dev
    container_name: speakai
    restart: always
    ports:
      - "8223:8000"
    volumes:
      - /home/ncadmin/speakai:/app/.gradio
      - /home/ncadmin/speakai_files:/app/gradio_cached_files
    environment:
      TTS_BASE_URL: https://api.mr5ai.com/v1
      VISION_BASE_URL: https://api.mr5ai.com/v1
      TTS_API_KEY: sk-XnbHbzBOmPYGHgL_BJdPUDEQaM4_hKpMiSmPAqAQosEmyzIgupzU084JZVQ
      VISION_API_KEY: sk-XnbHbzBOmPYGHgL_BJdPUDEQaM4_hKpMiSmPAqAQosEmyzIgupzU084JZVQ
      