services:
  web:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    environment:
      TTS_BASE_URL: ${TTS_BASE_URL}
      TTS_API_KEY: ${TTS_API_KEY}
      VISION_BASE_URL: ${VISION_BASE_URL}
      VISION_API_KEY: ${VISION_API_KEY}
    volumes:
      - pdf_to_podcast_gradio:/app/.gradio
      - pdf_to_podcast_gradio_cache:/app/gradio_cached_files

volumes:
  pdf_to_podcast_gradio:
  pdf_to_podcast_gradio_cache:
